### ISSUE TITLE
Reconsider `RecursiveOfType(T, Children(), Any)` 

### ISSUE THREAD

**Issue by jariji** [JuliaAPlavin/AccessorsExtra.jl#4]
>    `RecursiveOfType(out::Type, [optic=Children()]; [recurse::Type=Any])`
>
> Optic that references all values of type `out` located arbitrarily deep.
> 
> Recurses into values of type `recurse` (`Any` by default) using the specified inner `optic`.
> The default of `Children()` descends into all properties of objects, or into all elements of a collection.
> 
> ___Note:___ typically, when changing the `optic` parameter, the `recurse` type should be narrowed as well.

For an object unknown to the caller, it is not generally defined to access arbitrary properties; for an object known by the calling module, the caller knows the structure and can specify it in the recursion request. 

For example 

```jl
@modify(Float32, obj |> RecursiveOfType(Float64))
```

I'm not convinced this API is defined. Are we really allowed to access all recursive children of a `Quantity`? What does that mean?

**Comment by aplavin** [comment]
Not sure if I really understand the issue. 
It would help if you showed some actual (runnable or erroring) examples!

> For an object unknown to the caller, it is not generally defined to access arbitrary properties

What do you mean by "not generally defined"? `getproperty` seems to have a reasonably clear definition.

> Are we really allowed to access all recursive children of a Quantity?

Where exactly `Quantity` is in your example?

> I'm not convinced this API is defined. What does that mean?

I find this API well-defined and useful. Converting or otherwise accessing all objects of some required type within a larger object is a useful thing to have in many contexts.

**Comment by jariji** [comment]
The context that brought this to my attention is today's Slack discussion of replacing the numeric type of a `Unitful.Quantity`. Consider this usage:

```jl
julia> using Unitful, Accessors, AccessorsExtra

julia> obj = 1.0u"m"
1.0 m

julia> @modify(Float32, obj |> RecursiveOfType(Float64))
1.0f0 m
```

It recurses on the `Children()` of `obj`. But what are the `Children()` of `obj`? To find out, we naturally look at the docstring of its type.

```jl
julia> typeof(obj)
Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}

help?> Quantity
search: Quantity DimensionlessQuantity

  struct Quantity{T,D,U} <: AbstractQuantity{T,D,U}


  A concrete subtype of Unitful.AbstractQuantity.

  The type parameter T represents the numeric backing type. The type parameters D :: Unitful.Dimensions and U <:
  Unitful.Units.

  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  Quantity(x::Number, y::Units)


  Create a Quantity with numerical value x and units y.

  Example
  ≡≡≡≡≡≡≡

  julia> Quantity(5, u"m")
  5 m


  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  Quantity(period::Dates.FixedPeriod)


  Create a Quantity that corresponds to the given period. The numerical value of the resulting Quantity is of type
  Int64.

  Example
  ≡≡≡≡≡≡≡

  julia> using Dates: Second
  
  julia> Quantity(Second(5))
  5 s
``` 


It doesn't mention any public properties, so it is not legal to access any of them. What would it mean to do so?

**Comment by aplavin** [comment]
> so it is not legal to access any of them

That's a very strong and questionable implication IMO.

> What would it mean to do so?

Not sure what exactly you are asking about. The semantics of `propertynames` and `getproperty`?

Suggestions on how to implement this general functionality (eg, "extract all floats from an object") in alternative, better, ways are welcome!

**Comment by jariji** [comment]
In the example above, we know exactly which aspect of the object we're trying to change and we can target it specifically with `ustrip(obj)`. What is the use case for extracting all floats from an object irrespective of their meaning? 

I think the answer is when

- you know recursive `Children` on `obj` returns exactly the properties you want, and
- it will continue to do so in future releases, and
- there is not a more targeted way to get at exactly the properties you want.
 
For example, this could arise in a nested NamedTuple of parameter values, where each NamedTuple has different `propertynames`.

**Comment by aplavin** [comment]
Below just a few random usecases, where we don't know and don't want to specify the exact nested layout. And object(s) can be basically anything, not just namedtuples.

- Conversion. Say, I want to save my object so that it takes less space – replacing all Float64 with 32 or 16. Or, pass an object to GPU that only supports F32. Or, convert all fancy abstractstring types to regular Strings for compatibility.
This is `@modify(TargetType, obj |> RecursiveOfType(SourceType))`.

- Extraction. Say, I have `loss(::SomeType)` and want to minimize it. Optimization packages naturally work with vectors of numbers. So, I need functions that do `SomeType <-> Vector{Numbers}`. These are named `getall` and `setall`.

If you want to explicitly specify the locations where relevant values lie in the object, it's possible as well! But `RecursiveOfType` exists mainly for those cases where we want all :)

**Comment by jariji** [comment]
> where we don't know and don't want to specify the exact nested layout

> And object(s) can be basically anything

I don't think it's generally safe to modify properties of arbitrary objects without knowing whether they support that.

The docstring says 

> `propertynames(x)` may return only "public" property names that are part of the documented interface of `x`. If you want it to also return "private" property names intended for internal use, pass true for the optional second argument.

Since it says "may" and returns everything by default, I think most types probably return private properties by default and trying to modify or extract their internals is not permitted. 

If the whole `obj` tree is types that document the interface of their properties, then sure, but that's really rare.

**Comment by aplavin** [comment]
> Suggestions on how to implement this general functionality (eg, "extract all floats from an object") in alternative, better, ways are welcome!

**Comment by jariji** [comment]
Fair enough. 

For one thing, `propertynames` should be changed, if possible. https://github.com/JuliaLang/julia/issues/53717
